[build]
command = "npm run build" 
publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html/Chatting-Web---Next.js"
  status = 200
  force = false